application: mykqedchallenger
version: 1
runtime: python27
threadsafe: true
api_version: 1
module: browse

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /rest/.*
  script: main.APP

- url: (.*)/
  static_files: app\1/index.html
  upload: app
  mime_type: application/undefined

- url: (.*)
  static_files: app\1
  upload: app



skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$





