

runtime: python27
threadsafe: true
api_version: 1


handlers:

- url: /rest/.*
  script: main.APP

- url: (.*)/
  static_files: app\1/index.html
  upload: app
  mime_type: application/octet-stream

- url: (.*)
  static_files: app\1
  upload: app


libraries:
  - name: jinja2
    version: "2.6"
  - name: markupsafe
    version: "0.15"






