application: mykqedchallenger
version: 1
runtime: python27
threadsafe: true
api_version: 1


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /rest/.*
  script: main.APP

- url: (.*)/
  static_files: app\1/index.html
  upload: app


- url: (.*)
  static_files: app\1
  upload: app

libraries:
  - name: jinja2
    version: "2.6"
  - name: markupsafe
    version: "0.15"



skip_files:
- ^(.*/)?\.zip$
- ^(.*/)?\.bat$
- ^(.*/)?\.sh$
- ^(.*/)?\.md$
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^(.*/)grunt\.js
- ^(.*/)node_modules/(.*/)?
- ^(.*/)bower_components/(.*/)?
- ^scripts/(.*/)?
- ^test/(.*/)?
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py




